/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author LGNV
 */
public class frmHome extends javax.swing.JFrame {
    pnl_Tab_Home tab_home = new pnl_Tab_Home();
    pnl_Tab_Manager tab_manager = new pnl_Tab_Manager();
    /**
     * Creates new form frmHome
     */
    public frmHome() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        pnlCenter.add(tab_home, "home");
        pnlCenter.add(tab_manager, "manager");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new lgnvswing.lgnvPanel();
        btnHome = new lgnvswing.lgnvButton();
        btnQuanLi = new lgnvswing.lgnvButton();
        btnQuanLi1 = new lgnvswing.lgnvButton();
        pnlCenter = new lgnvswing.lgnvPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lgnvPanel1.setBackground(new java.awt.Color(66, 139, 202));
        lgnvPanel1.setLGNV_lineAllow(false);
        lgnvPanel1.setPreferredSize(new java.awt.Dimension(1253, 80));

        btnHome.setBackground(new java.awt.Color(66, 139, 202));
        btnHome.setBorder(null);
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_home_page_50px.png"))); // NOI18N
        btnHome.setText("Trang Chủ");
        btnHome.setLGNV_lineAllow(false);
        btnHome.setFocusable(false);
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnQuanLi.setBackground(new java.awt.Color(66, 139, 202));
        btnQuanLi.setBorder(null);
        btnQuanLi.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_bar_chart_50px.png"))); // NOI18N
        btnQuanLi.setText("Báo Cáo");
        btnQuanLi.setLGNV_lineAllow(false);
        btnQuanLi.setFocusable(false);
        btnQuanLi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuanLi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLiActionPerformed(evt);
            }
        });

        btnQuanLi1.setBackground(new java.awt.Color(66, 139, 202));
        btnQuanLi1.setBorder(null);
        btnQuanLi1.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_book_50px.png"))); // NOI18N
        btnQuanLi1.setText("Quản Lí");
        btnQuanLi1.setLGNV_lineAllow(false);
        btnQuanLi1.setFocusable(false);
        btnQuanLi1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuanLi1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLi1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lgnvPanel1Layout = new javax.swing.GroupLayout(lgnvPanel1);
        lgnvPanel1.setLayout(lgnvPanel1Layout);
        lgnvPanel1Layout.setHorizontalGroup(
            lgnvPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lgnvPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanLi1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanLi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(928, Short.MAX_VALUE))
        );
        lgnvPanel1Layout.setVerticalGroup(
            lgnvPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lgnvPanel1Layout.createSequentialGroup()
                .addGroup(lgnvPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLi1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(lgnvPanel1, java.awt.BorderLayout.PAGE_START);

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlCenter.setLGNV_lineAllow(false);
        pnlCenter.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        chooseTab("home");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnQuanLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLiActionPerformed
        
    }//GEN-LAST:event_btnQuanLiActionPerformed

    private void btnQuanLi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLi1ActionPerformed
        chooseTab("manager");
    }//GEN-LAST:event_btnQuanLi1ActionPerformed

    
    public void chooseTab(String nameTab){
        CardLayout layout = (CardLayout) pnlCenter.getLayout();
        layout.show(pnlCenter, nameTab);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lgnvswing.lgnvButton btnHome;
    private lgnvswing.lgnvButton btnQuanLi;
    private lgnvswing.lgnvButton btnQuanLi1;
    private lgnvswing.lgnvPanel lgnvPanel1;
    private lgnvswing.lgnvPanel pnlCenter;
    // End of variables declaration//GEN-END:variables
}
